# Generated by Django 5.1.7 on 2025-04-13 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('base_url', models.URLField(verbose_name='Base URL')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('language', models.CharField(help_text="ISO 639-1 language code (e.g., 'cs', 'uk')", max_length=10, verbose_name='Language')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'News Source',
                'verbose_name_plural': 'News Sources',
            },
        ),
        migrations.CreateModel(
            name='ScrapingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished at')),
                ('articles_found', models.IntegerField(default=0, verbose_name='Articles found')),
                ('articles_added', models.IntegerField(default=0, verbose_name='Articles added')),
                ('articles_updated', models.IntegerField(default=0, verbose_name='Articles updated')),
                ('errors', models.TextField(blank=True, verbose_name='Errors')),
                ('success', models.BooleanField(default=False, verbose_name='Success')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraping_logs', to='core.newssource', verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Scraping Log',
                'verbose_name_plural': 'Scraping Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('url', models.URLField(max_length=500, unique=True, verbose_name='URL')),
                ('summary', models.TextField(blank=True, verbose_name='Summary')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='Image URL')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('categories', models.ManyToManyField(blank=True, related_name='articles', to='core.category', verbose_name='Categories')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='core.newssource', verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['-published_at'], name='core_articl_publish_89e81b_idx'), models.Index(fields=['source', '-published_at'], name='core_articl_source__6c5b81_idx')],
            },
        ),
    ]
